kernel-module-vspm: remove force rebuild in setscene
Function vspm_sstate_check_func was added before to force kernel-module-vspm
rebuild when setscene running.
The purpose is to prevent missing header files vspm_public.h, which can happen
if setscene task of kernel-module-vspm runs before linux-renesas.
This missing subsequently makes build error in kernel-module-vspmif.

    [Reproduction method]
    bitbake kernel-module-vspmif
    rm -rf tmp
    bitbake kernel-module-vspmif

    vspm_if_main.c:72:25: fatal error: vspm_public.h: No such file or directory

Remove it now because:
- This issue does not happen anymore in current environment (tested 100 times)
- Due to an unknown reason, this force rebuild for kernel-module-vspm also
affect linux-renesas. Thus it costs much more time to run setscene tasks
(for rebuilding linux-renesas and many recipes that depend on linux-renesas)

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>