SDK: work-around build error in kernel-devsrc
Due to an unknown reason, below error happens in kernel-devsrc
when building SDK. This error has no impact to the system,
so Work-around it with this modification.

ERROR: kernel-devsrc-1.0-r0 do_package_qa: QA Issue: Architecture did not match (x86-64, expected AArch64) on /work/ebisu-poky-linux/kernel-devsrc/1.0-r0/packages-split/kernel-devsrc/usr/src/kernel/scripts/kconfig/conf.o
Architecture did not match (x86-64, expected AArch64) on /work/ebisu-poky-linux/kernel-devsrc/1.0-r0/packages-split/kernel-devsrc/usr/src/kernel/scripts/kconfig/zconf.tab.o [arch]

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>