cip-core: fix build error of glibc
This commit fix multiple build errors of glibc package
in recipes-cip-core.

The errors are:
- STAGING_DIR_TCBOOTSTRAP is not supported in this Yocto version
(will show error "tar: option requires an argument -- 'C'")
- Undefined reference to `libgcc_s_resume'
- Duplicate /usr/include/rpcsvc/rquota.h with rquota package

NOTE: to build this version user must set below settings
	PREFERRED_VERSION_glibc = "2.19"
	PREFERRED_VERSION_glibc-initial = "2.19"
	PREFERRED_VERSION_glibc-locale = "2.19"
	PREFERRED_VERSION_nativesdk-glibc = "2.19"
	PREFERRED_VERSION_nativesdk-glibc-initial = "2.19"
	PREFERRED_VERSION_nativesdk-glibc-locale = "2.19"
in local.conf or similar place
Without these settings, Yocto will build the original
version provided by poky instead

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>