kernel-module-qos: fix incomplete element type 'struct of_device_id'
fix compile issue : qos-module/files/qos/drv/qos_drv.c:186:34: error:
array type has incomplete element type 'struct of_device_id'

the issue is due to changes in source code of kernel 4.19

Signed-off-by: Binh Nguyen <binh.nguyen.uw@renesas.com>