SDK: fix build error due to missing locale
Fix a missing locale file in nativesdk-glibc-locale,
which causes below build error in SDK:

File: '/build/../poky/meta/lib/oe/sdk.py', lineno: 45, function: generate_locale_archive
     0041:    # Need to set this so cross-localedef knows where the archive is
     0042:    env = dict(os.environ)
     0043:    env["LOCALEARCHIVE"] = oe.path.join(localedir, "locale-archive")
     0044:
 *** 0045:    for name in os.listdir(localedir):
     0046:        path = os.path.join(localedir, name)
     0047:        if os.path.isdir(path):
     0048:            try:
     0049:                cmd = ["cross-localedef", "--verbose"]
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/build/tmp/work/ebisu-poky-linux/core-image-weston-sdk/1.0-r0/sdk/image/opt/poky/2.4.3/sysroots/x86_64-pokysdk-linux/usr/lib/locale'

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>