cip-core-buster: Fix build error in ppp due to wrong include
Some PCs meet build error in ppp due to a wrong include:

aarch64-poky-linux-gcc  ... -I/usr/include/openssl  ...   -c -o multilink.o multilink.c
cc1: warning: include location "/usr/include/openssl" is unsafe for cross-compilation [-Wpoison-system-directories]
In file included from pppcrypt.h:41:0,
                 from chap_ms.c:94:
/usr/include/openssl/des.h:91:9: error: unknown type name 'DES_LONG'
         DES_LONG deslong[2];

'-I/usr/include/openssl' is added for des.h, but this dir is not usable in cross-compiling.
Some PCs do not meet error if /usr/include/openssl does not exist in that PC.

Fix wrong include by modifying Makefile in ppp.
With this, does not need to copy des.h to usr/include anymore, remove do_compile_prepend()

Signed-off-by: Hung Tran <hung.tran.jy@renesas.com>